---
name: npm publish

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:

jobs:
  publish:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: okhiroyuki/composite-actions
          path: ./.github/actions/composite-actions
      - uses: ./.github/actions/composite-actions/npm-publish
        with:
          token: ${{ secrets.NPM_TOKEN }}
