---
name: npm publish

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
    paths:
      - "package.json"
  workflow_dispatch:

jobs:
  publish:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: okhiroyuki/composite-actions
          path: ./.github/actions/composite-actions
      - uses: ./.github/actions/composite-actions/npm-publish
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
